# Generated by Django 4.0.6 on 2022-07-23 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20220723_1858'),
    ]

    operations = [
    ]
