# Generated by Django 4.0.6 on 2022-07-21 02:59

from django.db import migrations

def populate_status(apps, schemaeditor):
    sections = {
        "Published": "Article published",
        "Pending Review": "Article under review",
        "Revision Requested": "Sent back to writer for revision",
        "Denied": "Article denied",
        "Draft": "Article being worked on",
    }
    Section = apps.get_model("articles", "Section")
    for name, desc in sections.items():
        section_obj = Section(name=name, description=desc)
        section_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_status_article_status'),
    ]

    operations = [
        migrations.RunPython(populate_status),
    ]
